import asyncio
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import func, or_, select, text
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models import Candidate, CandidateStatus, Score, SummaryStatus, User
from app.services.events import publish

PAGE_SIZE_DEFAULT = 20
PAGE_SIZE_MAX = 50


def _build_search_conditions(
    status: Optional[str] = None,
    role_applied: Optional[str] = None,
    skill: Optional[str] = None,
    keyword: Optional[str] = None,
):
    conditions = [Candidate.deleted_at.is_(None)]

    if status:
        conditions.append(Candidate.status == status)
    if role_applied:
        conditions.append(func.lower(Candidate.role_applied) == role_applied.lower())
    if skill:
        conditions.append(
            text(
                "EXISTS (SELECT 1 FROM json_each(candidates.skills) "
                "WHERE lower(json_each.value) = lower(:skill))"
            ).bindparams(skill=skill)
        )
    if keyword:
        like_pattern = f"%{keyword.lower()}%"
        conditions.append(
            or_(
                func.lower(Candidate.name).like(like_pattern),
                func.lower(Candidate.email).like(like_pattern),
            )
        )

    return conditions


async def search_candidates(
    db: AsyncSession,
    status: Optional[str] = None,
    role_applied: Optional[str] = None,
    skill: Optional[str] = None,
    keyword: Optional[str] = None,
    offset: int = 0,
    limit: int = PAGE_SIZE_DEFAULT,
) -> tuple[list[Candidate], int]:
    limit = max(1, min(limit, PAGE_SIZE_MAX))
    offset = max(0, offset)

    conditions = _build_search_conditions(
        status=status,
        role_applied=role_applied,
        skill=skill,
        keyword=keyword,
    )

    base_query = select(Candidate).where(*conditions)

    count_query = select(func.count()).select_from(base_query.subquery())
    total = (await db.execute(count_query)).scalar_one()

    result = await db.execute(
        base_query.order_by(Candidate.created_at.desc()).offset(offset).limit(limit)
    )
    candidates = list(result.scalars().all())
    return candidates, total


async def get_candidate_with_scores(db: AsyncSession, candidate_id: str) -> Optional[Candidate]:
    result = await db.execute(
        select(Candidate)
        .options(selectinload(Candidate.scores).selectinload(Score.reviewer))
        .where(Candidate.id == candidate_id, Candidate.deleted_at.is_(None))
    )
    return result.scalar_one_or_none()


async def create_score(
    db: AsyncSession, candidate_id: str, reviewer: User, category: str, score: int, note: str
) -> Score:
    new_score = Score(
        candidate_id=candidate_id,
        category=category,
        score=score,
        reviewer_id=reviewer.id,
        note=note,
    )
    db.add(new_score)
    await db.commit()
    await db.refresh(new_score)

    await publish(
        candidate_id,
        "score_created",
        {
            "id": new_score.id,
            "category": new_score.category,
            "score": new_score.score,
            "reviewer_id": new_score.reviewer_id,
            "reviewer_email": reviewer.email,
            "note": new_score.note,
            "created_at": new_score.created_at.isoformat() if new_score.created_at else None,
        },
    )
    return new_score


async def soft_delete_candidate(db: AsyncSession, candidate: Candidate) -> None:
    candidate.status = CandidateStatus.archived
    candidate.deleted_at = datetime.now(timezone.utc)
    await db.commit()


def _build_mock_summary(candidate: Candidate, scores: list[Score]) -> str:
    skills = ", ".join(candidate.skills) if candidate.skills else "no listed skills"
    if scores:
        average_score = sum(score.score for score in scores) / len(scores)
        score_line = (
            f"Average reviewer score so far is {average_score:.1f}/5 across {len(scores)} submission(s)."
        )
    else:
        score_line = "No scores have been submitted yet."
    return (
        f"{candidate.name} applied for {candidate.role_applied} with experience in {skills}. "
        f"{score_line} This summary was generated by a mock AI model for demo purposes."
    )


async def generate_ai_summary(session_factory, candidate_id: str) -> None:
    async with session_factory() as db:
        try:
            await asyncio.sleep(2)

            candidate = await get_candidate_with_scores(db, candidate_id)
            if candidate is None:
                return

            summary = _build_mock_summary(candidate, candidate.scores)
            candidate.ai_summary = summary
            candidate.ai_summary_status = SummaryStatus.completed
            await db.commit()

            await publish(
                candidate_id,
                "summary_completed",
                {"ai_summary": summary, "ai_summary_status": SummaryStatus.completed.value},
            )
        except Exception:
            candidate = await get_candidate_with_scores(db, candidate_id)
            if candidate is not None:
                candidate.ai_summary_status = SummaryStatus.failed
                await db.commit()
            await publish(
                candidate_id,
                "summary_failed",
                {"ai_summary_status": SummaryStatus.failed.value},
            )
